ConfigurationScreen As screen:
    Fill: =RGBA(4, 8, 29, 1)
    OnVisible: =false

    txtGoogleMapsKey As text:
        Default: |-
            ="AIzaSyC6-KTY49sqbO4LPibJVKGiHarDp3WKS58
            "
        Height: =70
        HintText: ="Enter Maps Key here"
        Size: =21
        Width: =560
        X: =40
        Y: =40
        ZIndex: =1

    txtImageWidth As text:
        Default: ="625"
        Format: =TextFormat.Number
        Height: =70
        HintText: ="Enter Maps Image Width here"
        Size: =21
        Width: =560
        X: =40
        Y: =145
        ZIndex: =2

    txtImageHeight As text:
        Default: ="1130"
        Format: =TextFormat.Number
        Height: =70
        HintText: ="Enter Maps Image Height here"
        Size: =21
        Width: =560
        X: =40
        Y: =242
        ZIndex: =3

    txtGoogleMapsID As text:
        Default: |-
            ="d91e9240925fdf0c
            "
        Height: =70
        HintText: ="Enter Maps Key here"
        Size: =21
        Width: =560
        X: =40
        Y: =325
        ZIndex: =4

    latitude As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =70
        Size: =21
        Text: |-
            ="latitude: " & Location.Latitude
        Width: =560
        X: =40
        Y: =436
        ZIndex: =5

    longitude As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =70
        Size: =21
        Text: |
            ="longitude: " & Location.Longitude
        Width: =560
        X: =40
        Y: =506
        ZIndex: =6

